### ISSUE TITLE
major regression with gradle 2.12 (NoSuchMethodError)

### ISSUE THREAD

**Issue by anthraxx** [thomaslee/gradle-jflex-plugin#3]
Hi, i noticed a major regression with gradle 2.12 that broke all builds using your jflex plugin, would it be possible to look into this and hopefully also release a compatible version as soon as possible?

The project where i first noticed this problem: https://github.com/JesusFreke/smali/issues/393

thank you very much, find attached the trace:

```
Caused by: java.lang.NoSuchMethodError: org.gradle.api.internal.file.DefaultSourceDirectorySet.<init>(Ljava/lang/String;Lorg/gradle/api/internal/file/FileResolver;)V
    at co.tomlee.gradle.plugins.jflex.JFlexVirtualSourceDirectoryImpl.<init>(JFlexVirtualSourceDirectoryImpl.java:14)
    at co.tomlee.gradle.plugins.jflex.JFlexPlugin$1.execute(JFlexPlugin.java:47)
    at co.tomlee.gradle.plugins.jflex.JFlexPlugin$1.execute(JFlexPlugin.java:39)
    at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:110)
    at co.tomlee.gradle.plugins.jflex.JFlexPlugin.configureSourceSets(JFlexPlugin.java:39)
    at co.tomlee.gradle.plugins.jflex.JFlexPlugin.apply(JFlexPlugin.java:31)
    at co.tomlee.gradle.plugins.jflex.JFlexPlugin.apply(JFlexPlugin.java:18)
    at org.gradle.api.internal.plugins.ImperativeOnlyPluginApplicator.applyImperative(ImperativeOnlyPluginApplicator.java:35)
    at org.gradle.api.internal.plugins.RuleBasedPluginApplicator.applyImperative(RuleBasedPluginApplicator.java:43)
    at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:137)
    at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:112)
    at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyType(DefaultObjectConfigurationAction.java:112)
    at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.access$200(DefaultObjectConfigurationAction.java:35)
    at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction$3.run(DefaultObjectConfigurationAction.java:79)
    at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.execute(DefaultObjectConfigurationAction.java:135)
    at org.gradle.api.internal.project.AbstractPluginAware.apply(AbstractPluginAware.java:46)
    at org.gradle.api.plugins.PluginAware$apply.call(Unknown Source)
    at org.gradle.api.internal.project.ProjectScript.apply(ProjectScript.groovy:35)
    at org.gradle.api.Script$apply$0.callCurrent(Unknown Source)
    at build_b85mvysfpqvernutfvf0lsyvk.run(/build/smali/src/smali-2.1.2/smali/build.gradle:33)
    at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:91)
    ... 58 more


BUILD FAILED
```

**Comment by anthraxx** [comment]
Just a side note, accidentally I stumbled across a similarly named jflex plugin that fixed exactly this issue and release a new version. maybe you can look at the commit as it fixed the very same issue: https://github.com/jprante/gradle-plugin-jflex/commit/fafef1c6ca2388938b4e195fa65dcff258295333

**Comment by anthraxx** [comment]
@thomaslee no offense and surely I understand its not weekend yet, but can we get a rough ETA for a new released version that is compatible with gradle 2.12? My intention is that this issue currently holds back an distribution update for another package using the jflex-plugin.

**Comment by thomaslee** [comment]
cheers @anthraxx -- see #4.
